---
# Whenever a semver tag is pushed,
# create a library release and publish it in the NPM registry

name: NPM Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      # https://github.com/actions/checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      # https://github.com/actions/cache
      - name: Setup Dependency Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install Dependencies
        run: npm install

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
